<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!-- Reference v2.0.0 of Dot.QuartzDashboard (project reference for development, NuGet for consumers) -->
  <ItemGroup>
    <ProjectReference Include="..\QuartzDashboard\QuartzDashboard.csproj" />
    <ProjectReference Include="..\QuartzDashboard.Sqlite\QuartzDashboard.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.2" />
  </ItemGroup>

</Project>
